# Generated by Django 5.0.4 on 2024-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=255)),
                ('city_or_municipality', models.CharField(max_length=100)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crops_planted', models.CharField(max_length=255)),
            ],
        ),
    ]
