# Generated by Django 5.0.4 on 2024-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gis', '0002_rename_farm_farmmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
