# Generated by Django 5.0.4 on 2024-04-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gis', '0003_farmmodel_latitude_farmmodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmodel',
            name='place_id',
            field=models.FloatField(null=True),
        ),
    ]
