# Generated by Django 5.0.4 on 2024-04-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gis', '0004_farmmodel_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farmmodel',
            name='place_id',
        ),
        migrations.AddField(
            model_name='farmmodel',
            name='farm_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
