# Generated by Django 5.0.4 on 2024-04-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gis', '0005_remove_farmmodel_id_remove_farmmodel_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmodel',
            name='farm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
